//todo create and drop influx table from script
//todo add a test for the demo
//todo some validation

resetDB()

//TODO write macros like this one

//#define MARKOV => law ("markovLaw" + i++) ofType MarkovLaw changeStateFrequency 1 / 20.s

//law "markovLaw" ofType MarkovLaw changeStateFrequency 1 / 20.s withMatrix([[0.3, 0.2, 0.5], [0.15, 0.8, 0.05], [0.25, 0.25, 0.5]])
int i = 0

//MARKOV withMatrix([[0.3, 0.2, 0.5], [0.15, 0.8, 0.05], [0.25, 0.25, 0.5]])
//MARKOV withMatrix([[0.3, 0.7], [0.15, 0.85]])

simpleExpression = { x ->
    return (x < 5) ? 2 * (x**2) : 4
}

//law "polynomialLaw" ofType FunctionLaw withExpressions simpleExpression
//dataSource "poly2" ofType FunctionLaw itReturns "STRING" withExpressions (["Shiny": "x>0.22","Rainy" : "x<0.22"])

//sensorLot "markovLot" sensorsNumber 2 law "markovLaw0" frequency 1 / s
//sensorLot "polynomialLot" sensorsNumber 2 law "polynomialLaw" frequency 1 / s
//sensorLot "randomLot" sensorsNumber 2 law "randomLaw" frequency 1 / s

def r = randomLaw "randomLaw"
sensorLot "s2" with {
    sensorsNumber 2
    law r
    frequency 1 / min
}

/*sensorLot "s2" with {
    sensorsNumber 10
    law {
        randomLaw "randomLaw"
    }
    frequency 20 / s
}*/

play "s2"

//String filepath = "/home/fpastor/GroovyProjects/SSL-al/groovy/src/main/resources/rawdata/inconsistent.csv"
//replay "file1" path path columns([t: 0, s: 1, v: 8]) offset 10.s
/*replay "file1" with {
    path filepath
    columns([t: 0, s: 1, v: 8])
    offset 10.s
}*/
runSimulation "10/02/2018 09:25:00", "10/02/2018 09:30:00"